_commit: v0.1.0-14-g04294ae
_src_path: git@github.com:benwebber/open-data-toronto-copier.git
name: RentSafeTO
project: open-data-toronto-rentsafe
repo: benwebber/open-data-toronto-rentsafe
slug: rentsafe
url: https://open.toronto.ca/dataset/apartment-building-evaluation/
