name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - v**
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Make database
        run: |-
          make
      - name: Publish database
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
      - name: Log into container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set image version
        run: |
          echo "VERSION=${GITHUB_REF_NAME/#v}" >>"${GITHUB_ENV}"
      - name: Build and push image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: >
            ghcr.io/${{ github.repository }}:latest,
            ghcr.io/${{ github.repository }}:${{ env.VERSION }},
            ghcr.io/${{ github.repository }}:${{ github.sha }}
