---
name: Fetch latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 5 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Fetch latest data
      uses: benwebber/get-ckan-package@v1
      with:
        url: https://ckan0.cf.opendata.inter.prod-toronto.ca/
        package_id: 2b98b3f3-4f3a-42a4-a4e9-b44d3026595a
        output_dir: data
        resource_ids: '["3ad76a8c-0518-4df2-b94e-8c747d62f8c1"]'
    - name: Push latest data
      run: |-
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add data
        git commit -m 'Update RentSafe data' || exit
        git push
